
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health
        
spring:
  datasource:
    #url: jdbc:postgresql://dbpostgresql:5432/productdb
    url: jdbc:postgresql://127.0.0.1:5432/productdb
    username: 
    password: 
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
 
  
  flyway:
    enabled: true
    #url: jdbc:postgresql://dbpostgresql:5432/productdb
    url: jdbc:postgresql://127.0.0.1:5432/productdb
    schemas: productdb
    user: 
    password: 
            