
server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health
        
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:productdb}
    username: ${DB_USERNAME:demouser}
    password: ${DB_PASSWORD:demouser}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:productdb}
    schemas: ${DB_DB:productdb}
    user: ${DB_USERNAME:demouser}
    password: ${DB_PASSWORD:demouser}
            