---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    app: product-app
spec:
  type: LoadBalancer
  selector:
    app: product-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
