---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    app: product-app
spec:
  selector:
    app: product-app
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
